SUPABASE_URL = "https://fglmdmfjdyfqiggpaeex.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnbG1kbWZqZHlmcWlnZ3BhZWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTY3OTgsImV4cCI6MjA2NDE5Mjc5OH0.9Snx9CVM_zaaDeouRA1nR122JqOfd0cI30_8Z21b-hY"
